DM-36402: Draft technote on AP period-finding
lsst-dm/dmtn-221 pull request #2
Opened 2022-11-21 17:00 UTC by AndyTza

Preliminary version of the AP period-finding results are ready for review.

2023-01-04 23:51 UTC, ebellm requested changes
Lots of comments throughout, mostly textual

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The baselined timeseries features to be computed in Alert Production include a Lomb-Scargle periodogram ran on two classes of variable systems: RR Lyrae and Eclipsing Binaries.
```suggestion
The baselined timeseries features to be computed in Alert Production include a Lomb-Scargle periodogram.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Based on a simulated LSST-like cadence light curves taken from the Extended LSST Astronomical Time-series Classification Challenge (ELAsTiCC) we perform an end-to-end test to characterize the periodi
```suggestion
Based on a simulated LSST-like cadence light curves taken from the Extended LSST Astronomical Time-series Classification Challenge (ELAsTiCC) we perform an end-to-end test to characterize the periodicity recovery on the Alert Production multi-band light curves of two classes of variable systems: RR Lyrae and Eclipsing Binaries..
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +In both variable classes, we found that a single-band Lomb-Scargle implementation yields to a low fraction of recovered periods, with a significant preference on the simple periodic phenomena such as
```suggestion
In both variable classes, we found that a single-band Lomb-Scargle implementation yields a low fraction of recovered periods.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +We also invetigated the results from a multi-band Lomb-Scargle and found an increased fraction of recovered periodicities above 15$\%$ for the eclipsing binaries, and over 80$\%$ for the RR Lyrae sta
```suggestion
We also investigated the results from a multi-band Lomb-Scargle periodogram and found an improved fraction of recovered periodicities: above 15$\%$ for the eclipsing binaries, and over 80$\%$ for the RR Lyrae stars.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +We also asses the computational and scientific performance of several configurations on simulated alert data and find that our current configuration scales linearly with the number of detections whil
```suggestion
We also asses the computational and scientific performance of several configurations on simulated alert data and find that our current configuration scales linearly with the number of detections when using a heuristic frequency grid.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The characterization of periodicity from time-series is a fundamental constraint to numerous astrophysical applications.
```suggestion
The characterization of periodicity from time-series is a prerequisite to numerous astrophysical applications.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Phenomenologically, estimating the periodicity and its significance can shed light on stellar pulsation theory \citep{Antonello:Antonello81}, distance estimation and mapping of the Galaxy through the
```suggestion
Phenomenologically, estimating the periodicity and its significance can shed light on stellar pulsation theory \citep{Antonello:Antonello81}, distance estimation and mapping of the Galaxy through the period-luminosity relationship \citep{Skowron:Skowron2019}, and constrain fundamental parameters of stellar binaries \citep{Farinella:Farinella1979} and stellar rotation \citep{Walkowicz:Walkowicz13}.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +
We need a sentence or two here summarizing AP.

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +However, no study to date has demonstrated the recovery period distribution of more complex periodic phenomena such as eclipsing binaries in real-time.
```suggestion
However, no study to date has demonstrated the recovery period distribution of more complex periodic phenomena such as eclipsing binaries in Alert Production specifically.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +In this study we use the training set Extended LSST Astronomical Time-series Classification Challenge (ELAsTiCC) light curves with a 12 month history that will best mimic the calculations performed f
```suggestion
In this study we use the labelled training set from the Extended LSST Astronomical Time-series Classification Challenge (ELAsTiCC) light curves with a 12 month history that will match the DIASource history length available in AP.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +In short, ELAsTiCC is a real-time pipeline for generating mock photometric alerts at the expected LSST rate.
```suggestion
ELAsTiCC is a data challenge generating mock photometric alerts similar in format to those expected from LSST.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Most importantly, the ELAsTiCC light curves simulate force photometry alerts which we recommend all time series features to be calculated upon.
```suggestion
Most importantly, the ELAsTiCC light curves simulate forced photometry alerts appropriate for computations of periodic variability.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +While a small EB sample size limits the search for a larger distribution in periodicities, it remains nonetheless useful to see the periodicity recovery rates at different sampling phases.
```suggestion
While a small EB sample size limits the search for a larger distribution in periodicities, it remains nonetheless useful to see the periodicity recovery rates at different sampling intervals.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Both RRL's and EB's represent the extrema of simple and complex periodic sources that will throughly test the underlying ability of the periodogram to find the correct period.
I'd just drop this sentence.

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +While other quasi-periodic sources, such as AGN, might be of importance, in this study we aim to answer if computing the periodogram on periodic phenomena is possible.
```suggestion
While other periodic and quasi-periodic sources are of importance, in this study we aim to assess the technical feasibility of periodicity computation in AP.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +  \caption{The above panels demonstrate the multi-band light curves simulated from ElasTiCC using RR lyrae (left panel) and eclipsing binaries (right panel).
```suggestion
  \caption{The above panels show example multi-band light curves simulated by ElasTiCC for RR Lyrae (left panel) and eclipsing binaries (right panel).
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The LSST will be search for periodic phenomena across both short and long timescales.
```suggestion
LSST science users are interested in periodic phenomena on both short and long timescales.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +High resolution period grids can also be very computationally expensive that is not feasible in the 60 second data latency of AP.
```suggestion
High resolution period grids can also be very computationally expensive that is not feasible in the 60 second processing latency of AP.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Inevitably, large searches in period space without an a priori will require an heuristic approach to generating an appropriate period grid that will account for the light curve characteristics.
```suggestion
Inevitably, large searches in period space require an heuristic approach to generating an appropriate period grid that will account for the light curve characteristics.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +We first consider the case of the canonical single-band detections from AP.
```suggestion
We first consider the case of the period searches using only detections in a single filter band from AP.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +For the average LSST field, our results are independent of the selected photometric filter due the uniformity of sky coverage from all filters.
the band distribution isn't uniform, though--u-band gets less, for example.

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +We extrapolated the highest power period from the periodogram and compare it to the true period.
```suggestion
We obtained the highest power period from the periodogram and compare it to the true period.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Since we are re-sampling the same underlying models it is possible that the light curve re-sampling is not aduete enough to identify correct large periods.
```suggestion
Since we are re-sampling the same underlying models it is also possible that the light curve re-sampling is not adequate to identify correct large periods.
```

(I'm not sure this seems like the likely cause of this issue though...)

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +While the RR Lyrae exhibit at larger Fourier modeling modes more aliasing, overall the recovery fraction of correctly identified periods is larger compared to the EBs.
```suggestion
While the RR Lyrae exhibit more aliasing at larger Fourier modeling modes, overall the recovery fraction of correctly identified periods is larger compared to the EBs.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +For both light curve models, we consistently found in each model configuration that the average correctly identified period coincides with a larger number of detections.
what does "average" mean here?

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The true challenge of this approach comes from the more complex light curves such as the EBs with more phase variation.
what do you mean by "phase variation?"

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +  \caption{We show the injected (true period) versus recovered highest peak in the periodogram for a sample of 1000 $r$-band detections from RR lyrae and eclipsing binaries.
```suggestion
  \caption{We show the injected (true period) versus recovered highest peak in the periodogram for a sample of 1000 $r$-band lightcurves from RR Lyrae and eclipsing binaries.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +On average, there will be 30 detections in each photometric band per 12 month light curve history.
I'm confused by this--there are 6 filters and an average of 80 epochs a year--how do you get 30?  (maybe this is the rolling cadence??)

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Given the sampling rate of LSST per pointing, this entails that the majority of single-band AP light curves would be too undersampled in order to compute a high confidence periodicity.
```suggestion
Given the sampling rate of LSST per pointing, this implies that the majority of single-band AP light curves would have too few samples to compute a high-confidence periodicity.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Even with a low completeness, computing the Lomb-Scargle periodogram on single-band time series alerts, this will likely outperform any other known survey due to the large survey volume.
what do you mean by "outperform?"

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Next, we test the multi-band Lomb-Scargle periodogram implementation adapted in \textsc{gatspy} to our ELAsTiCC light curves.
```suggestion
Next, we test the multi-band Lomb-Scargle periodogram implementation adapted in \texttt{gatspy} to our ELAsTiCC light curves.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +  \includegraphics[width=0.6\textwidth]{figures/multi_vs_single_rec_frac.pdf}
I think this is the wrong image?

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +One common diagnostic used in the literature is the False Alarm Probability (FAP) a given peak in the power spectrum.
```suggestion
One common diagnostic used in the literature is the False Alarm Probability (FAP) of a given peak in the power spectrum.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The FAP measures the probability uncertainty associated with the selected peak under the null hypothesis.
```suggestion
The FAP estimates the probability that a periodogram peak with power greater than that of the selected peak would occur under the null hypothesis that the lightcurve contains only noise.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Generally, the reported FAP for a specific period peak can be used to inform the user of its a trustworthy detection.
```suggestion
The reported FAP can help users assess the trustworthiness of a reported period.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +A constraint on the number of detections and FAP is adequate to achieve a complete catalogue of periodic phenomena.
Not sure I believe this sentence?  Let's delete it.

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Given the fast AP latency and number of periodic sources, a significant real-time bootstraping is likely not feasible for AP.
```suggestion
Given the fast AP latency and number of periodic sources, a significant real-time bootstrapping is likely not feasible for AP.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +A more popular approach is to use parametric FAP estimators that asymptotically converge to similar distributions of bootstraping FAP approaches.
```suggestion
A more feasible approach is to use parametric FAP estimators that asymptotically converge to similar distributions of bootstraping FAP approaches.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +A sophisticated approach suggested by \citet{Baluev:Baluev2008} which uses extreme value statistics to compute an upper bound of the false alarm probability for the alias-free case:
```suggestion
A sophisticated approach suggested by \citet{Baluev:Baluev2008} uses extreme value statistics to compute an upper bound of the false alarm probability for the alias-free case:
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The derivation of such form is beyond the scope of this paper, and we suggest future studies to explore if such solution exists.
```suggestion
The derivation of such form is beyond the scope of this paper, and we suggest future studies to explore if such a solution exists.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The Baluev approximation has already been applied in other studies such as \citet{Suveges:Suveges15} and is suggested as a computationally inexpensive and reliable form to approximate the FAP.
We should consider also https://ui.adsabs.harvard.edu/abs/2020A&A...635A..83D, likely in preference to Baluev.

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The more complex issue arrises from the complex mathematics that involve the derivation of the Baluev approximation for the multi-band Lomb-Scargle form.
```suggestion
However, an extension of this formulation to the multi-band Lomb-Scargle periodogram is needed.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +To test whether the Baulev approximation holds true for the multi-band light curves we attempt to correlate a conventional bootstraping significance approach with the Baluev form.
```suggestion
To test whether the Baulev approximation holds true for the multi-band light curves we attempt to correlate a conventional bootstrapping significance approach with the Baluev form.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +In this section we bench mark the average run time of the Lomb-Scargle periodogram implementation from gatspy.
```suggestion
In this section we benchmark the average run time of the Lomb-Scargle periodogram implementation from \texttt{gatspy}.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The balancing act of high periodocity accuracy while confining the calculations within the AP timeframe is a challenging act.
```suggestion
Our challenge is to obtain high periodocity accuracy while confining the calculations within the AP timeframe.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +While coarse period grids  and complex models can achieve more accurate periods, this will not be possible to do with AP.
```suggestion
While fine period grids  and complex models can achieve more accurate periods, this will not be possible to do with AP.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +The current gatspy, which is a pure Python based implementation of the Lomb-Scargle periodogram, scales as  $\mathcal{O}$[N] algorithm for small N and becomes $\mathcal{O}$[N$^2$] at larger trial per
```suggestion
The current \texttt{gatspy}, which is a pure Python based implementation of the Lomb-Scargle periodogram, scales as  $\mathcal{O}$[N] algorithm for small N and becomes $\mathcal{O}$[N$^2$] at larger trial periods.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +In practice, this would work for any given filter given the rolling cadence of LSST.
delete

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +We find that the finer period grids are better at identifying the correct periods while also keeping the run time at about one second per light curve with a 12 photometric history.
```suggestion
We find that the finer period grids are better at identifying the correct periods while also keeping the run time at about one second per light curve with a 12 month photometric history.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +
Add some conclusions--what should we baseline?

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Interestingly, the question of run time also raises the question of how many periodic sources do we expect per LSST pointing and limiting magnitude depth...
```suggestion
Determining acceptable runtime per source within AP latency will require analysis of how many periodic sources we expect per LSST pointing in the densest region, along with choices about how many historical detections should be required before period-finding is conducted.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +We suspect that the main culpruit of low completeness to be the average low SNR that computed for the ELAsTiCC eclipsing binary sample.
```suggestion
We suspect that the main culprit of low completeness to be the average low SNR that computed for the ELAsTiCC eclipsing binary sample.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +As a proof of concept, we can validate a possible scenario of high SNR eclipsing binary light curves using the cadence strategy of op$\_$sims v.1.7 using an in-house light curve building tool.
```suggestion
As a proof of concept, we can validate a possible scenario of high SNR eclipsing binary light curves using the cadence strategy of op$\_$sim v.1.7 using a custom light curve building tool.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +Using the 62 EB models, we sample each model at the $ugrizy$ cadence separation described by the op$\_$sims v.1.7 simulation.
```suggestion
Using the 62 EB models, we sample each model at the $ugrizy$ cadence separation described by the op$\_$sim v.1.7 simulation.
```

2023-01-04 23:51 UTC, ebellm commented on DMTN-221.tex
> +To estimate the expected SNR from a source with magnitude $m$ by assuming a Gaussian distribution of photons we apply the standard $m5snr$ equation.
```suggestion
To estimate the expected SNR from a source with magnitude $m$ by assuming a Gaussian distribution of photons we apply the standard $m_5$ SNR equation.
```

2023-01-18 19:18 UTC, AndyTza commented on DMTN-221.tex
> +Both RRL's and EB's represent the extrema of simple and complex periodic sources that will throughly test the underlying ability of the periodogram to find the correct period.
agreed!

2023-01-18 19:22 UTC, AndyTza commented on DMTN-221.tex
> +For the average LSST field, our results are independent of the selected photometric filter due the uniformity of sky coverage from all filters.
Agreed. Perhaps we should include that the u-band will likely suffer from low completeness due to its smaller coverage.

2023-01-18 19:42 UTC, AndyTza commented on DMTN-221.tex
> +The true challenge of this approach comes from the more complex light curves such as the EBs with more phase variation.
I think what I meant here is that EB's have more complex underlying models.

2023-01-18 19:44 UTC, AndyTza commented on DMTN-221.tex
> +For both light curve models, we consistently found in each model configuration that the average correctly identified period coincides with a larger number of detections.
Agreed, this isn't very clear. In this statement, I wanted to highlight that for single-band Lomb Scargle we found that on average the recovery fraction average was higher for light curves that had higher single-band detections. I will fix this section.

2023-01-18 20:41 UTC, AndyTza commented on DMTN-221.tex
> +On average, there will be 30 detections in each photometric band per 12 month light curve history.
I have identified the issue here. This plot was out of date, but it still seems like the average number of detections across all fingers in ELAsTiCC (using op_sim v.1.7) is around 62 per light curve. I agree, [based on Opsim v.1.7 the median number of detections per year should be ~80](http://astro-lsst-01.astro.washington.edu:8081/allMetricResults?runId=676#Nvisit%20Summary).

I will have to investigate why we're missing ~20 visits per light curve!

2023-02-15 20:19 UTC, merged